version: "3.8"

services:
  daemon1:
    image: nt
    ports:
      - 8080:8080
    command: ["-a", "0.0.0.0", "-p", "8080"]
  daemon2:
    image: nt
    ports:
      - 8081:8081
    command: ["-a", "0.0.0.0", "-p", "8081"]
  envoy:
    image: envoyproxy/envoy-dev:4e486e1d336fd0e67ea4f1ee27475daaf6291321
    ports:
      - 10001:10001
      - 9901:9901
    volumes:
      - ./envoy/envoy-demo.yaml:/etc/envoy/envoy.yaml