version: "3.8"

services:
  daemon1:
    # This is how you set your DNS name as well as container name. NOTE: don't use 'hostname'. We can now use 
    # 'container_name' as an envoy cluster endpoint.
    container_name: daemon1
    image: nt
    ports:
      - 8080:8080
    command: ["-a", "0.0.0.0", "-p", "8080"]
  daemon2:
    container_name: daemon2
    image: nt
    ports:
      - 8081:8081
    command: ["-a", "0.0.0.0", "-p", "8080"]
  envoy:
    container_name: envoy_proxy
    image: envoyproxy/envoy-dev:4e486e1d336fd0e67ea4f1ee27475daaf6291321
    ports:
      - 10000:10000
      - 9901:9901
    volumes:
      - ./envoy/envoy-demo.yaml:/etc/envoy/envoy.yaml

# This is how you set your own network name. Default is '<project-folder>_default'.
networks:
  default:
    name: daemon_network